### ISSUE TITLE
Community section: create calendar of Umbraco related events

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/OurUmbraco#182]
This includes:

  - Festivals
  - Meetups
  - Things like CodeCabinn
  - Niels is speaking at a conference
  - etc

Should be able to filter by type so we can list only festivals or only meetups.

We should be able to do some content management on festivals from the backoffice to provide a description, link, maybe a banner.

RSS feed of events would be an added bonus.

We can re-use the design from the roadmap so we have a timeline with events on it.

**Comment by abjerner** [comment]
@nul800sebastiaan wouldn't storing festivals etc. as content in Umbraco put some extra work on the HQ? Couldn't it just be a JSON file editable via GitHub? (I'm just asking, as you probably know better what works the best)

Also, meetups are working fine now, so it should probably be an aggregated list of some sort, so some content is curated while other content (like Meetups) are imported automatically.

**Comment by nul800sebastiaan** [comment]
@abjerner Our communications team at HQ would love to create the content and maintain it!
Yep, indeed, the calendar will just list whatever is currently available from meetups into it, no need to re-invent the wheel there! :)

**Comment by abjerner** [comment]
Figured it would be a good idea to to have the discussion here instead of Gitter.

I had a quick play with a timeline based calendar. I've used the existing logic for meetups, while the part for festivals is somewhat hardcoded.

![image](https://user-images.githubusercontent.com/3634580/37373011-26434288-2715-11e8-8f80-224c61774a5e.png)

I kinda have reinvented the CSS and HTML for the timeline, as the existing code from releases have an issue with the vertical alignment:

![image](https://user-images.githubusercontent.com/3634580/37373219-0bd4d992-2716-11e8-91f6-b27d7de613fc.png)

Btw, where would a calendar live? As a new level 2 section, or as level 3 sub section for **Community**?

**Comment by nul800sebastiaan** [comment]
Wow. Didn't realize you were going to pick this up already!

This looks great!! Yes, I imagined it would replace the current Meetups page under **community** so it becomes **community/calendar**. I was thinking we can put festivals and other random events under that page so that we just need to list the children, mixed with the meetups that are already available.
