### ISSUE TITLE
Group blogposts

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#221]
I was wondering if we should group the blogposts on this page?
https://our.umbraco.org/community/blog-posts/

E.g. blogposts from https://umbraco.com/blog/ , but also from the christmas calendar 🎅 

For example it would be great to have blog posts from https://24days.in/umbraco-cms/2017/ grouped by year.

Alternatively a filter option to filter blogposts by "Umbraco HQ", "24.days.in", etc.

**Comment by abjerner** [comment]
@bjarnef Yes, I think there should be some sort of grouping or filtering.

But in order for this to work properly, I think we need to keep an archive of blog posts instead of just pulling and showing the recent ones. I posted some thoughts about that here: https://github.com/umbraco/OurUmbraco/issues/222

**Comment by nul800sebastiaan** [comment]
Yep, would love to archive and group!

**Comment by nul800sebastiaan** [comment]
Duplicate of #222
