### ISSUE TITLE
Avatar unknown issue on the Karma Leaderboard

### ISSUE THREAD

**Issue by Mivaweb** [umbraco/OurUmbraco#224]
Seems that an Our member has an issue with his avatar causing this:

![capturess](https://user-images.githubusercontent.com/13479920/38407630-8de1334c-397a-11e8-9535-4689cbc160ef.jpg)

Shouldn't this member have a default avatar?

/Michaël

**Comment by Mivaweb** [comment]
Ok on the profile page of this member, a default avatar is rendered and visible.

**Comment by nul800sebastiaan** [comment]
I'm refactoring all avatars at the moment, should be fixed soon :)

**Comment by nul800sebastiaan** [comment]
There we go, the avatar of this person has been fixed and avatar code has been centralized. We're also not using Gravatar at all any more so that we don't leak any data to them (a privacy update).

![image](https://user-images.githubusercontent.com/304656/38454281-7d8b14fa-3a64-11e8-81cc-7ad3c9d77b4c.png)

**Comment by Mivaweb** [comment]
Thanks for the help!
