### ISSUE TITLE
Access member profiles by nickname

### ISSUE THREAD

**Issue by greystate** [umbraco/OurUmbraco#227]
It has always bugged me that an Our member's profile is only accessible using their `id`.

I always have to do a search just to find Janae's or Fuji's () profile - heck, I can't even remember my own id :-)

Wouldn't it be possible to create a **ContentFinder** that could find the right member, given their GitHub user or Twitter handle? E.g. for me, they're the same, but `https://our.umbraco.org/member/greystate`  would work anyway.

I can see two problems:

1. It _is possible_ for someone to have the same GitHub username as someone else's Twitter handle but that should be very few, but even then, we could maybe show a list of the two?

2. Some members have neither a GitHub user nor a Twitter handle - but their id-URL would still work then...

Would there be any security-related issues with this?

**Comment by abjerner** [comment]
@greystate I think this would be awesome.

I looked a bit at the code, and we can update the existing macro partial (yes, the public profile is a macro) along with a small rewrite rule. `Web.config` already has:

```xml
<rule name="MemberProfile">
  <match url="member/(\d+)" />
  <action type="Rewrite" url="member/?id={R:1}" />
</rule>
```

so we can add:

```xml
<rule name="MemberProfileUsername">
  <match url="member/(\w+)" />
  <action type="Rewrite" url="member/?username={R:1}" />
</rule>
```

If we use the GitHub username, the code for finding the member could look something like:

```C#
// Get a reference to the member searcher
BaseSearchProvider searcher = ExamineManager.Instance.SearchProviderCollection[Constants.Examine.InternalMemberSearcher];

// Initialize new search criteria for the GitHub username
ISearchCriteria criteria = searcher.CreateSearchCriteria();
criteria = criteria.RawQuery(String.Format("github:{0}", username));

// Make the search in examine
ISearchResults results = searcher.Search(criteria);

// Get the member based on the ID from the search result
if (results.TotalItemCount > 0)
{
    member = Members.GetById(results.First().Id);
}
```

I tested this on my local Our installation, and it works like a charm. But it wont work if the GitHub username is numeric (not sure if GitHub supports that), as the Our numeric ID rewrite rule will be matched first.

I think we should either stick entirely with the GitHub username (not Twitter) or let members claim their username independently of GitHub and Twitter.

@nul800sebastiaan Any thoughts on this? I be happy to make a pull request with my code for the GitHub username.

Technically there may be an issue since two members currently are able to specify the exact same GitHub username, and my code snippet will just pick the first member found i Examine. So I could specify `greystate` as my GitHub username just to annoy Chriztian. But again, this may not be an issue as I'm not really that kind of guy ;)

If anyone else wish do the pull request (maybe their first 👍 ), feel free to use my code snippet. Most of the code that need's to be adjusted lives in `/OurUmbraco.Site/Views/Partials/Members/PublicProfile.cshtml`.

**Comment by nul800sebastiaan** [comment]
Seems fine to me. At some point I would really like to implement a proper link to GitHub and Twitter by redirecting people through those two sites to prove that they own the account, for now this should be more than enough.

I'll check out the changes when I have some time!

**Comment by nul800sebastiaan** [comment]
Note: it IS indeed possible to have github usernames that are just numbers.

**Comment by abjerner** [comment]
@greystate @nul800sebastiaan any ideas for a URL syntax specific for username then? We could go with `/members/{username}` instead (members in plural).

Others could be:

`/member/@{username}`
`/member/github:{username}`

Or only use @ for numeric GitHub usernames:
`/member/@1337` <-- GitHub username
`/member/1337` <-- Our user id

**Comment by abjerner** [comment]
Also, as @greystate writes, it can hard to find specific members. So should there be a global members page where we could search for members?

I don't whether there are any privacy concerns for something - if so, it could be opt-in. Besides, it should be possible to find members via Google - it's just a bit harder/cumbersome.

**Comment by greystate** [comment]
Really awesome @abjerner !

I'd prefer using the GitHub username, even though I'm pretty sure that there are more members with a Twitter account than there are with a GitHub account (?).

It's a damn shame we can't just go with `/member/abjerner/` but I guess the `/@abjerner/` version could work almost as well :-)

**Comment by abjerner** [comment]
@greystate We could make it so that the @ is only used for numeric GitHub usernames:

/member/@1337 <-- GitHub username
/member/1337 <-- Our user id
/member/abjerner <-- GitHub username

But then again, Our has a number of member pages which technically could collide with GitHub usernames as well:

![image](https://user-images.githubusercontent.com/3634580/38697911-9a449584-3e93-11e8-8f24-bea09b19a030.png)

So things will break if a member has `import` as username :persevere:

Perhaps we're back at switching to `/members/{username}`. I think this would make sense - also if there will be a members overview page. We could then also switch to `/members/id:{memberId}` going forward.

If I remember correctly, Sebastiaan also talked about rewriting the main community page to be an aggregated list of blogs, meetups, videos etc. If so, the community map could be moved to a members overview page instead:

![image](https://user-images.githubusercontent.com/3634580/38698163-68cd4252-3e94-11e8-84ac-fe33f06dd8c1.png)

(just thinking out load)

<hr />

Anyways, regardless of how the URL will look, we need to update all places in the code that generates the "legacy" URLs for a member.

Also, the old URL should still continue to work. So we should probably also specify a canonical link - but to the old URL or the new URL? A user may later remove the GitHub username from their profile, and thus any indexed links to the member profile will die.

**Comment by greystate** [comment]
I'm totally on the `@githubuser` bandwagon now - it would work with the least amount of caveats :)

Main reason to have this in the first place is for anyone to be able to go directly to someone's profile page without having to remember an ID... Heck, I could even live with a 302 redirect to the current (id) version, to be honest :-)

So my proposal would be to rewrite `/member/@\w+` to the profile page (if it matches a github username) and add the old id version as the canonical link.

**Comment by abjerner** [comment]
@nul800sebastiaan regarding my last comment, do you have any thoughts on the URL structure? Going forward, I think it could make sense to use `/members/{username}` and `/members/id:{memberId}` for member URLs. One of them should then redirect to the other - or both should work, but use canonical URLs to specify to primary URL of the two (whichever one that is).

I'm also a bit keen on a members overview page, which could live on `/members`. What is the HQ's take on this? Personally I wouldn't have a problem with being shown in a global list, or that other members could search for me - and I think most of the active and "regular" Our members feel the same way. But I'm also not sure whether there are any privacy concerns that I'm not seeing.

**Comment by nul800sebastiaan** [comment]
Forgot to close this issue after merging #237
