### ISSUE TITLE
The "Activity in threads you participated in" list does not seem to be updating

### ISSUE THREAD

**Issue by mortenbock** [umbraco/OurUmbraco#248]
I have participated in some newer threads, and even received emails about new activity in them. But they do not seem to be showing in this dashboard?

![image](https://user-images.githubusercontent.com/1760256/40923085-261cd338-6814-11e8-87f5-cc77070e496f.png)

**Comment by BatJan** [comment]
I experience that it's working kinda random...I see a mix of new and old threads in my list, which is quite confusing. Don't know if it may be a weird caching issue?

**Comment by greystate** [comment]
Maybe it's just being ordered wrong? 

I searched the source for "ACTIVITY IN THREADS YOU PARTICIPATED IN" and _followed the rabbit_ to end up here:

https://github.com/umbraco/OurUmbraco/blob/166329bd6c3b8fcceaa907a72f244445ff2fe920/OurUmbraco/Forum/Services/TopicService.cs#L221-L230

There's a couple of `OrderByDescending()` further down, but I don't know how it all works, so can't tell if there's caching involved or if the `Topic.Updated` could be in a wrong non-sortable format...

**Comment by villian** [comment]
There is a 5 minutes cache for this block. I think it's confusing because of caching. Ordering made here:

```
            sql
                .OrderByDescending<Topic>(x => x.Updated)
                .OrderByDescending<Comment>(comment => comment.Created);

```

**Comment by nul800sebastiaan** [comment]
Yeah, as @villian says it's due to caching. If anyone wants to take a stab at fixing it that would be cool, it should be possible to temporarily add things to the cache while we wait for it to expire I think, not sure?

For now I'll close it as it does work "eventually", but feel free to open a PR for this. I've put the `idea` label on it so we can revisit it later when we have some more time to spare.
