### ISSUE TITLE
Add placeholder text to search input on search page

### ISSUE THREAD

**Issue by bjarnef** [umbraco/OurUmbraco#444]
On search page the seach input should have a placeholder text.

https://our.umbraco.com/search
https://our.umbraco.com/search?q=
https://our.umbraco.com/search?q=Umbraco%208

![image](https://user-images.githubusercontent.com/2919859/59093144-7ca3bc00-8913-11e9-87c6-892f41bb3751.png)

When no results are found, it could maybe show some topics or maybe list popular search terms?

**Comment by nul800sebastiaan** [comment]
Sure that would definitely be helpful.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

As for the second feature request, we don't track "popular" search terms and if the term yields absolutely no results then there's also no context on giving them different results.. Open to suggestions, but I don't think there's much to do about that.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/pull/457
