### ISSUE TITLE
Can't upload avatar

### ISSUE THREAD

**Issue by dhymik** [umbraco/OurUmbraco#463]
I am unable to successfully upload an avatar picture for my our.umbraco account. Although the upload finishes without error, no avatar picture is being shown. I tried various file types (jpg, png), file sizes, and browsers, all the same.
Regards, Mikael

**Comment by nul800sebastiaan** [comment]
Hi @dhymik - I just tried on https://our.umbraco.com/member/profile/ and it works perfectly. 

I'm using Chrome, which browser are you using?

I'm assuming it's some kind of browser, browser plugin or firewall issue. Do you see any errors in the browser console?

**Comment by dhymik** [comment]
Hi @nul800sebastiaan,

I tested on Chrome and Firefox, doesn't work on my machine.

I'll test on a different machine and in a different location and get back to you.

**Comment by dhymik** [comment]
Hi @nul800sebastiaan,

I tried on a different computer with Chrome, and it works. I tried on my computer with old IE11 and it works - avatar changed.

I tried on my computer with Chrome (latest) and all extensions / plugins disabled (starting chrome with --disable-extensions --disable-extensions), and it does **_not_** work. No errors in console, firewall disabled.

**Comment by nul800sebastiaan** [comment]
Alright @dhymik - I'm sorry to hear it's not working, but you are the only one I know of with this problem. Therefore, I can only conclude there is a problem in your specific environment that you'll need to investigate.

**Comment by NelCapeTown** [comment]
I have exactly the same issue.  I get a notification telling me that my avatar is too small and blurry (because it is still the default avatar auto-selected when I created my account.)
I hover on the avatar and click on "Change Image"
I get to choose my file and when I click it says uploading, but then suddenly everything is back to before I tried to change the picture.  I have now tried it several times on the current update of Chrome, but then also tested in Edge & Firefox.  It does not work in any browsers.
