### ISSUE TITLE
Official Umbraco blogs, date format issue?

### ISSUE THREAD

**Issue by jvtroyen** [umbraco/OurUmbraco#570]
Blogs by Umbraco.com seem to have a date issue on https://our.umbraco.com/community/blog-posts/. 
March 12th is displayed as December 3rd. Maybe wrong/ambiguous format in the RSS feed?

**Comment by jvtroyen** [comment]
Date-format in Umbraco RSS feed seems to be MM/dd/yyyy HH:mm:ss
(e.g. `<pubDate>3/12/2020 12:00:00 PM</pubDate>`)

Other RSS feeds contain e.g. `<pubDate>Wed, 15 Apr 2020 05:40:35 PDT</pubDate>`.
I'm guessing the code that parses these feeds uses multiple formats to decode the date? dd/MM and MM/dd are the biggest ambiguous formats when representing dates.

**Comment by abjerner** [comment]
As far as I remember, this is because @nul800sebastiaan just ran the job manually. IIRC the thread then doesn't get the correct culture. It should be fixed once the job runs automatically.

I think Seb and I discussed this at some point, but I can't remember the outcome. So it probably wasn't fixed - hence why we're seeing it now 😮

**Comment by nul800sebastiaan** [comment]
Yeah it will correct itself soon, can't remember how often it runs 😊

**Comment by nul800sebastiaan** [comment]
There we go, it has corrected itself. I don't often run it manually, so I'm not too concerned about this. It runs automatically every hour on the hour.

**Comment by jvtroyen** [comment]
Seems indeed nothing to worry about. 
Thanks.
