### ISSUE TITLE
Can't rename a package

### ISSUE THREAD

**Issue by skttl** [umbraco/OurUmbraco#605]
I just tried to rename one of my packages, but the changes don't get saved. I also tried updating the description, and that worked.

**Comment by jmayntzhusen** [comment]
Related pr: https://github.com/umbraco/OurUmbraco/pull/550

Ran into a general problem we have where when I created this. The problem is all package names are based on content nodes in the backoffice, so if you change your package name to fx `Super Package` and that already exists it would instead be called `Super Package(1)`.

This is also currently the case when creating a package though - having some sort of validation built in would be ideal but was a bit more than I attempted to do in my original pr so haven't been back to it 🙂

Will check if we can't just merge this in as with its faults it is still better than nothing..

**Comment by jmayntzhusen** [comment]
@skttl 

This should work now, with the little issue mentioned above for duplicate packages. I will create a separate issue about adding some better name validations both when creating and updating a package 🙂
