### ISSUE TITLE
Property editor links are broken in search engines.

### ISSUE THREAD

**Issue by CharlesInteractive** [umbraco/OurUmbraco#700]
## Step to reproduce

1. Search google or bing for a property editor. I first noticed this when searching for [nested content documentation on google](https://www.google.com/search?q=umbraco+nested+content&oq=umbrac&aqs=chrome.0.69i59l3j69i60l3j69i65l2.1028j0j7&sourceid=chrome&ie=UTF-8).
2. The first result from my search was "Nested Content, Getting Started - Our Umbraco"
3. Clicked the result and got taken to Backoffice Overview, not nested content.

The same thing happens when I searched google for multi url picker and media picker. The best result for each took me to Backoffice Overview, not their appropriate Our Umbraco page.

**Comment by sofietoft** [comment]
Thanks for the report @CharlesInteractive !

Earlier this week, we moved everything from the "Getting Started" section into a new "Fundementals" section.
Unfortunately, we didn't get the rewrites quite right, so that's why you're ending up on the Backoffice article when your link is actually pointing at something a little deeper in that section 😅 
You can find all the property editor articles here: https://our.umbraco.com/documentation/Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/

I promise you that we're looking into resolving it asap! 💪

**Comment by CharlesInteractive** [comment]
Thanks Sofie. I wasn't sure if you all were aware.

I'll close this though, I now realize this probably isnt the place to report issues with live Our 🙃

**Comment by sofietoft** [comment]
Ah, perhaps not 🙈 
But thanks for reporting it still!

I've made a PR, that should fix the rewrites (https://github.com/umbraco/OurUmbraco/pull/701) 🤞

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/OurUmbraco/pull/701 - there's still some browser caching but that should hopefully expire soon, a hard refresh works. Thanks @sofietoft! 👍 

And no problem to report this here, that is perfect!
