### ISSUE TITLE
I'm also unable to update my profile pic/Avatar.

### ISSUE THREAD

**Issue by NelCapeTown** [umbraco/OurUmbraco#736]
I have exactly the same issue.  I get a notification telling me that my avatar is too small and blurry (because it is still the default avatar auto-selected when I created my account.)
I hover on the avatar and click on "Change Image"
I get to choose my file and when I click it says uploading, but then suddenly everything is back to before I tried to change the picture.  I have now tried it several times on the current update of Chrome, but then also tested in Edge & Firefox.  It does not work in any browsers.
And then - just to make sure it was not something on my PC, I used Chrome (latest up-to-date version) on my Android mobile phone to try get the photo updated.  And I received exactly the same error.

I created a new issue since I saw that the original issue mentioned below is Closed.

_Originally posted by @NelCapeTown in https://github.com/umbraco/OurUmbraco/issues/463#issuecomment-960613974_

**Comment by nul800sebastiaan** [comment]
I've tried to upload your github avatar (https://avatars.githubusercontent.com/u/4562349?v=4) and that seems to work. Maybe the photo you're trying to use has something wrong with it?

https://user-images.githubusercontent.com/304656/141750062-ea69ee82-272f-40fc-ba84-5695ec6fd9a0.mp4

So maybe try with that image as I did? Alternatively, the only thing I can think of is that your network has something weird going on preventing you from uploading the file maybe?

In any case, do try to see what happens when you upload with the browser's F12 tools open you should be seeing errors in either the console or the network tab that could give us a clue as to what is going on.

**Comment by nul800sebastiaan** [comment]
It seems like you had problems with your ESET anti-virus, looks like that's fixed now so I'll close this one.
